spring:
  application:
    name: 01blog
  datasource:
    url: jdbc:postgresql://localhost:5431/mydb
    username: 01blog
    password: 01blog
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
security:
  jwt:
    secret-key: ussra
    expiration-time: 86400000

