spring:
  application:
    name: 01blog
  datasource:
    url: jdbc:postgresql://localhost:5431/mydb
    username: 01blog
    password: 01blog
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-time: 86400000
logging:
  level:
    org:
      springframework:
        security: DEBUG
file:
  upload-dir: uploads/avatars
