spring:
  application:
    name: 01blog

  datasource:
    url: jdbc:postgresql://localhost:5432/01blog
    username: postgres
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 8080